// <auto-generated />
using CurrencyBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyBackend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201130135713_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CurrencySource.Models.Currency", b =>
                {
                    b.Property<string>("CharCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Previous")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("CharCode");

                    b.ToTable("CurrencyList");
                });

            modelBuilder.Entity("CurrencySource.Models.CurrencyTracked", b =>
                {
                    b.Property<string>("CharCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CharCode");

                    b.ToTable("TrackedCurrencyList");
                });
#pragma warning restore 612, 618
        }
    }
}
